#Program for computing the solution of the quadratic equation ax^2 + bx + c = 0...

a = float(input("Coefficient a:"))
b = float(input("Coefficient b:"))
c = float(input("Coefficient c:"))
d = (b**2) - 4 * a * c  #Taking the discriminant of the equation...
if a != 0:
    x1 = (-b + (d)**0.5) / (2 * a)  #Formula for calculating the first root of the equation....
    x2 = (-b - (d)**0.5) / (2 * a)  #Formula for calculating the second root of the equation....
    print("The roots of the quadratic equation is:", x1 ,"and", x2)  
else:
 print("No possible solution is there for this equation.")  
